### ISSUE TITLE
Making CODE_OF_CONDUCT.md

### ISSUE THREAD

**Issue by haruki7049** [SuteraVR/.github#3]
- `.github/CODE_OF_CONDUCT.md`

https://docs.github.com/ja/communities/setting-up-your-project-for-healthy-contributions/adding-a-code-of-conduct-to-your-project

**Comment by tukiminya** [comment]
Any update?

**Comment by haruki7049** [comment]
There is no recent update. I looked in various logs for information on this, but there didn't seem to be any logs left. @see2et, what was going on with this issue?
